### ISSUE TITLE
No action visible on clicking Submit button

### ISSUE THREAD

**Issue by crtahlin** [datafund/dr-editor-sample#1]
On clicking Submit button (see screenshot) even with all the fields filled out, no action seem to happen (there is no error, but no result either).

Expected: a JWT token to be generated. 

![image](https://user-images.githubusercontent.com/1554520/58956545-dc2c8b00-879e-11e9-80c0-6cb071efa69a.png)

**Comment by markus-rettro** [comment]
Button removed.
