### ISSUE TITLE
Make CR viewer wider

### ISSUE THREAD

**Issue by crtahlin** [datafund/dr-editor-sample#10]
It seems that if the default width of the CR viewer would be about twice the current width, this would make the viewer much more usable from (all info shown without scrolling).

![image](https://user-images.githubusercontent.com/1554520/61561733-f630dd00-aa6f-11e9-839d-68ac77c7746a.png)

Try to make the width cca. 2x the current, to accomodate the full display (of the default project file, bcs I guess it depends on the project used).

**Comment by markus-rettro** [comment]
Entire modal window was stretched to bootstrap's "xl" width.
