### ISSUE TITLE
After clicking button for actions, give feedback on status of action

### ISSUE THREAD

**Issue by crtahlin** [datafund/dr-editor-sample#14]
Currently, many buttons do not "report" on how the action went - success, failure, ... The user does not know that something happened in the background. There should be some action after the click, to inform the user that the click was "detected" at least, if not the result of the action, which would be best.

This applies to all the buttons:

![image](https://user-images.githubusercontent.com/1554520/61562398-86bbed00-aa71-11e9-84f1-21d502a1a284.png)

![image](https://user-images.githubusercontent.com/1554520/61562453-a18e6180-aa71-11e9-981b-9cedd729294b.png)

**Comment by markus-rettro** [comment]
Done.
