### ISSUE TITLE
Merge parts for signing and sending

### ISSUE THREAD

**Issue by crtahlin** [datafund/dr-editor-sample#16]
Should we merge these two parts under same "+": 

![image](https://user-images.githubusercontent.com/1554520/61562955-cd5e1700-aa72-11e9-81cb-ee40cc2ce2f1.png)

Otherwise the receiver's Fairdrop name might not be visible / gets hidden if someone is only signing & sending.

(Then we would probably also remove or change the top most heading "Decentralized storage and sending".)

**Comment by tfius** [comment]
hm... we could merge under Send Consent

**Comment by markus-rettro** [comment]
Merged. Looks like this now: 
![Screenshot 2019-07-22 at 13 44 53](https://user-images.githubusercontent.com/4500148/61630042-eb9c6080-ac86-11e9-9317-6a8d16dcbee4.png)
