### ISSUE TITLE
Tables displaying sent and received CRs should be different

### ISSUE THREAD

**Issue by crtahlin** [datafund/dr-editor-sample#20]
The tables showing sent and received CRs should be different, as per spec:

![image](https://user-images.githubusercontent.com/1554520/62857604-5a099700-bcf8-11e9-9f35-766334d6759e.png)

E.g., the "sent" one shows the "Data principal" that the CR was sent to, while the "received" one shows the "Data controller" that sent the CRs.

Currently, they both have the same labels for column headings:

![image](https://user-images.githubusercontent.com/1554520/62857799-cedcd100-bcf8-11e9-8695-a2d4cc10b572.png)

The content also seems incorrect, at least for the "sent" table. I have tried sending the receipt to "crtahlin10" , and the column lists as the principal "crtahlin9" (which is actually the Data controller, sending the CR).

**Comment by crtahlin** [comment]
Also, the table for the Data principal tab has the wrong header / columns (it should have info for the Data principal):

![image](https://user-images.githubusercontent.com/1554520/63336079-d1fe3f80-c33e-11e9-8e75-9781cebef520.png)

**Comment by tfius** [comment]
fix
