### ISSUE TITLE
Status messages are delayed

### ISSUE THREAD

**Issue by crtahlin** [datafund/dr-editor-sample#21]
Not quite sure of the issues, but it seems status messages that are supposed to be shown on the tab for Data principal are shown all at once after switching to the Data controller tab. See screenshot:

![image](https://user-images.githubusercontent.com/1554520/63337586-826d4300-c341-11e9-840a-a58ec20253ea.png)

Where two status messages are shown immediately after switching tabs (had a situation with even more messages at once).

**Comment by tfius** [comment]
fix on data user view
