### ISSUE TITLE
Fix funcionality of "send" button for data user tab

### ISSUE THREAD

**Issue by crtahlin** [datafund/dr-editor-sample#22]
Maybe related to #7 

There is something happening after clicking "Send", but in console there are errors listed and the app does not seem to function properly afterwards.

Button in question:
![image](https://user-images.githubusercontent.com/1554520/63847729-b3c3bf80-c98e-11e9-9640-be20918a0da4.png)

Errors:
![image](https://user-images.githubusercontent.com/1554520/63847744-bf16eb00-c98e-11e9-8a50-2072b5ac7a17.png)

**Comment by tfius** [comment]
fix
