### ISSUE TITLE
Check name existance while typing it

### ISSUE THREAD

**Issue by crtahlin** [datafund/dr-editor-sample#23]
There seems to be no Fairdrop name check while typing it as the account name to receive the consent receipt. 
This causes an error when clicking "Send" and some strange succession of messages. It is OK, if the user manually refreshes the table, at which time the name is checked, and sending after that.

The checks for name existance should be made while typing the name. If the name does indeed not exists, sending should not be executed.

![image](https://user-images.githubusercontent.com/1554520/63848370-ffc33400-c98f-11e9-9269-ec217f0bb901.png)

**Comment by tfius** [comment]
fix
