### ISSUE TITLE
Make UX for demo better by moving some elements

### ISSUE THREAD

**Issue by crtahlin** [datafund/dr-editor-sample#3]
- hide the "Submit" button on the "CR Editor" page (it currently does not work as expected, see #1, but is actually not need for the demo as the CR JWT can be generated elsewhere)
- add a button "Download JWT" to the left of the "Decode JWT" (on click it should offer to download the "consent-receipt.jwt.cr" file)
-  make the part under "Encode" as a separate section named "Encode JWT"
- rename section "JWT Token" to "Encoded JWT" (T in JWT already stands for token)
- move the button "Decode JWT" to a separate section and show the decoded content immediately after the button
- the "Verify signature" should be a separate section; also, remove showing of decoded token here (as it is already shown in another section)

**Comment by crtahlin** [comment]
Edit:
- the name of the file when clicking "Download JWT" should be: {consent_timestamp}.cr.jwt

**Comment by crtahlin** [comment]
Edit: 
- make the RS256 the first of the two tabs (default first choice)
- separate "Encode JWT" from the FormData section
If possible without too much effort, make a larger separation (maybe as tabs) for the parts about: Contents (JSONSChema, UISchema, FormData), Encoding (Encode JWT, ...), Decoding (decoding token verifying signature, ...)

**Comment by markus-rettro** [comment]
Done.
