### ISSUE TITLE
Fix funcionality of "send" button for data user tab

### ISSUE THREAD

**Issue by crtahlin** [datafund/dr-editor-sample#7]
There seems to be no action behind the "Data controller - send CR JWT to Data principal" button.

![image](https://user-images.githubusercontent.com/1554520/61542392-c4a11d00-aa41-11e9-86e6-13f11d74ef60.png)

Nothing visible happens upon click. Would expect a notification of action happening (or error / warning otherwise). Also, upon succesfull send, there should be a row listed in the Data controller sent Data Receipts table.

Note: currently it seems (not 100%) that if clicking this button, then also the button "Blockchain sign & send ... " does not work. Maybe there is still some action pending in the background?

**Comment by markus-rettro** [comment]
Fixed.
