### ISSUE TITLE
Make tables visible without scrolling

### ISSUE THREAD

**Issue by crtahlin** [datafund/dr-editor-sample#9]
If possible, make "default" display width enough to accomodate the table width, so that whole table is visible without scrolling:

![image](https://user-images.githubusercontent.com/1554520/61561434-478c9c80-aa6f-11e9-9580-e66e93662d71.png)

**Comment by markus-rettro** [comment]
Container was set to "fluid", so now it occupies entire browser window width. I'm attaching screenshot:
![Screenshot 2019-07-22 at 13 52 08](https://user-images.githubusercontent.com/4500148/61630403-ebe92b80-ac87-11e9-856b-92eb55bc51dc.png)
